# Generated by Django 2.2.1 on 2019-07-02 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=20)),
                ('profession', models.CharField(default='', max_length=20)),
                ('experience', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Average'), (3, 'Expert')], null=True)),
                ('hourly_rate', models.CharField(default='', max_length=10)),
                ('total_project', models.CharField(default='', max_length=10)),
                ('english_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Average'), (3, 'Expert')], null=True)),
                ('availability', models.CharField(default='', max_length=10)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
