# Generated by Django 2.2.1 on 2019-06-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
