# Generated by Django 2.2.1 on 2019-06-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190630_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
